
package com.rentcar.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarsImplService", targetNamespace = "http://soap.rentcar.com/", wsdlLocation = "http://localhost:8080/soap/cars?wsdl")
public class CarsImplService
    extends Service
{

    private final static URL CARSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARSIMPLSERVICE_EXCEPTION;
    private final static QName CARSIMPLSERVICE_QNAME = new QName("http://soap.rentcar.com/", "CarsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/cars?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARSIMPLSERVICE_WSDL_LOCATION = url;
        CARSIMPLSERVICE_EXCEPTION = e;
    }

    public CarsImplService() {
        super(__getWsdlLocation(), CARSIMPLSERVICE_QNAME);
    }

    public CarsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARSIMPLSERVICE_QNAME, features);
    }

    public CarsImplService(URL wsdlLocation) {
        super(wsdlLocation, CARSIMPLSERVICE_QNAME);
    }

    public CarsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARSIMPLSERVICE_QNAME, features);
    }

    public CarsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cars
     */
    @WebEndpoint(name = "CarsImplPort")
    public Cars getCarsImplPort() {
        return super.getPort(new QName("http://soap.rentcar.com/", "CarsImplPort"), Cars.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cars
     */
    @WebEndpoint(name = "CarsImplPort")
    public Cars getCarsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.rentcar.com/", "CarsImplPort"), Cars.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARSIMPLSERVICE_EXCEPTION!= null) {
            throw CARSIMPLSERVICE_EXCEPTION;
        }
        return CARSIMPLSERVICE_WSDL_LOCATION;
    }

}
